### ISSUE TITLE
Feat: load the system version requirements from the addon's meta.yaml

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/catalog#395]
A new feature of automatically finding available addon‘s version has been added to KubevVela's repository. 

> https://github.com/kubevela/kubevela/issues/4181

In order to adapt this feature, we need to add a `system` field to the `meta.yaml` file to record the system version requirements corresponding to a certain version of the addon. 

```yaml
name: example
version: 1.0.1
description: Extended workload to do continuous and progressive delivery
icon: https://raw.githubusercontent.com/fluxcd/flux/master/docs/_files/weave-flux.png
url: https://fluxcd.io
system: "vela>=1.4.0; kubernetes>=1.20.0"
```

This information will be loaded when synchronizing the addon package, and finally loaded to the `index.yaml` corresponding to the addon repository.

Can you provide better advice on where to load system version requirements? @wangyikewxgm  @wonderflow
