### ISSUE TITLE
Update FluxCD Addon

### ISSUE THREAD

**Issue by kferrone** [kubevela/catalog#445]
I seem to be coming across an issue which was fixed in FluxCD but the Vela addon still has the issue. 

I opened this issue with FluxCD: https://github.com/fluxcd/helm-controller/issues/518

I verified the CRD in Flux is different than what was installed for me:
https://github.com/fluxcd/helm-controller/blob/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml

**Comment by kferrone** [comment]
Just for fun, I added the following to the crd in the kubeconfig property:
```yaml
                      key:
                        description: Key in the Secret, when not specified an implementation-specific
                          default key is used.
                        type: string
```
