### ISSUE TITLE
Provide dex connector for GitHub Enterprise

### ISSUE THREAD

**Issue by TommyHwang** [kubevela/catalog#464]
### Background

Currently, dex connector is available for public GitHub use.

GitHub Enterprise requires additional host settings in `dex-connector-def.yaml`.

### Related link

https://dexidp.io/docs/connectors/github/#github-enterprise

### Need to be changed

https://github.com/kubevela/catalog/blob/e07244fe0ab185eeecf564fd759f37a369271749/addons/dex/definitions/dex-connectors-def.yaml#L60-L67

#### def

```yaml
                github?: {
                        // +usage=GitHub client ID
                        clientID: string
                        // +usage=GitHub client secret
                        clientSecret: string
                        // +usage=GitHub redirect URI
                        redirectURI: string
                }
```

#### ui-schema

https://github.com/kubevela/catalog/blob/e07244fe0ab185eeecf564fd759f37a369271749/addons/dex/schemas/component-uischema-config-dex-connector.yaml#L3

```yaml
- jsonKey: github
  sort: 3
  uiType: Ignore
  validate:
    required: true
  conditions:
    - jsonKey: type
      op: "=="
      value: "github"
  subParameters:
    - jsonKey: clientID
      uiType: Password
      sort: 1
    - jsonKey: clientSecret
      uiType: Password
      sort: 3
    - jsonKey: redirectURI
      sort: 5
```
